# Generated by Django 5.2.16 on 2026-07-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Leave blank for unlimited', null=True),
        ),
    ]
