# Generated by Django 5.2.16 on 2026-08-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_school_eventparticipation_school'),
        ('users', '0003_student_blood_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipation',
            unique_together={('event', 'student')},
        ),
    ]
