# Generated by Django 5.2.16 on 2026-08-30 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventparticipation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Leave blank for unlimited', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
