# Generated by Django 5.2.16 on 2026-08-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_accesslog_school_entryexitlog_school_visitor_school'),
        ('users', '0004_alter_student_admission_no_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entryexitlog',
            unique_together={('student', 'entry_time')},
        ),
    ]
