# Generated by Django 5.2.16 on 2026-07-22 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('finance', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='users.student'),
        ),
        migrations.AddField(
            model_name='feehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feehistory',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.fee'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.class'),
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='finance.feestructure'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.fee'),
        ),
    ]
