# Generated by Django 5.2.16 on 2026-07-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_obj', 'subject', 'teacher')},
        ),
    ]
