# Generated by Django 5.2.16 on 2026-08-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_class_school_classsubject_school_room_school_and_more'),
        ('tenants', '0004_school_database_alias'),
        ('users', '0003_student_blood_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'name', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('class_obj', 'name')},
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('class_obj', 'subject', 'teacher'), name='uniq_classsubject_teacher'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher__isnull', True)), fields=('class_obj', 'subject'), name='uniq_classsubject_no_teacher'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uniq_subject_school_code'),
        ),
    ]
