# Generated by Django 5.2.16 on 2026-08-30 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_category_school_menuitem_school_orderitem_school'),
        ('tenants', '0004_school_database_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price at time of order', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('school', 'name')},
        ),
    ]
