# Generated by Django 5.2.16 on 2026-08-30 06:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_school_documenttype_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('user', 'doc_type')},
        ),
    ]
