# Generated by Django 5.2.16 on 2026-08-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_backfill_default_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('default_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'features',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SchoolFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.feature')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='tenants.school')),
            ],
            options={
                'db_table': 'school_features',
                'unique_together': {('school', 'feature')},
            },
        ),
    ]
