# Generated by Django 5.2.16 on 2026-08-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_feature_schoolfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='database_alias',
            field=models.CharField(default='default', help_text="Django DATABASES alias where this school's rows live. 'default' = shared Neon; other values = dedicated shards.", max_length=50),
        ),
    ]
