# Generated by Django 5.2.16 on 2026-08-30 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_school_database_alias'),
        ('transport', '0003_bus_school_busstop_school_busstudent_school_and_more'),
        ('users', '0003_student_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together={('route', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='busstudent',
            unique_together={('student',)},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('school', 'name')},
        ),
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.UniqueConstraint(fields=('school', 'bus_no'), name='uniq_bus_school_no'),
        ),
    ]
