# Generated by Django 5.2.16 on 2026-08-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_bus_bus_no_alter_bus_capacity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together={('route', 'name'), ('route', 'stop_order')},
        ),
    ]
