# Generated by Django 5.2.16 on 2026-08-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_classsubject_unique_together_and_more'),
        ('tenants', '0004_school_database_alias'),
        ('users', '0003_student_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'admission_no'), name='uniq_student_school_admission'),
        ),
    ]
