# Generated by Django 5.2.16 on 2026-07-22 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leavehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavehistory',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hr.leave'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='hr.employee'),
        ),
    ]
