# Generated by Django 5.2.16 on 2026-07-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_balance',
            field=models.IntegerField(default=20, help_text='Remaining annual leave days'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
