# Generated by Django 5.2.16 on 2026-07-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAutoChecking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ai_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by_ai', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ai_auto_checking',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('term', 'Term'), ('quiz', 'Quiz'), ('annual', 'Annual')], max_length=20)),
                ('date', models.DateField()),
                ('total_marks', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.CharField(max_length=10, unique=True)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'grade_scale',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('short', 'Short'), ('long', 'Long')], max_length=20)),
                ('answer_text', models.TextField(blank=True, help_text='Model answer')),
                ('marks', models.IntegerField()),
                ('options', models.JSONField(blank=True, help_text='MCQ options', null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('marks_obtained', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True)),
                ('selected_option', models.CharField(blank=True, help_text='For MCQ', max_length=255)),
                ('is_correct', models.BooleanField(blank=True, help_text='AI checked', null=True)),
                ('marks_awarded', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_answers',
            },
        ),
    ]
