# Generated by Django 5.2.16 on 2026-08-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classsubject_unique_together'),
        ('exams', '0003_alter_result_grade_alter_result_percentage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('class_obj', 'subject', 'exam_type')},
        ),
    ]
