# Generated by Django 5.2.16 on 2026-08-30 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_result_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
