# Generated by Django 5.2.16 on 2026-08-30 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_analyticssnapshot_school_automationlog_school_and_more'),
        ('tenants', '0004_school_database_alias'),
        ('users', '0003_student_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentengagement',
            name='engagement_score',
            field=models.IntegerField(default=0, help_text='0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='parentengagement',
            name='interaction_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='parentengagement',
            name='ptm_attendance',
            field=models.IntegerField(default=0, help_text='Count', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentgoal',
            name='progress',
            field=models.IntegerField(default=0, help_text='0-100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='skillmapping',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='studentskill',
            unique_together={('student', 'skill')},
        ),
    ]
