# Generated by Django 5.2.16 on 2026-08-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_parentengagement_engagement_score_and_more'),
        ('tenants', '0004_school_database_alias'),
        ('users', '0004_alter_student_admission_no_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analyticssnapshot',
            unique_together={('school', 'metric_name', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='automationlog',
            unique_together={('rule', 'triggered_at')},
        ),
        migrations.AlterUniqueTogether(
            name='automationrule',
            unique_together={('school', 'rule_name')},
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('student', 'prediction_type', 'prediction_date')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('student', 'type', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='studentgoal',
            unique_together={('student', 'goal_type', 'target')},
        ),
    ]
