# Generated by Django 5.2.16 on 2026-07-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTMAttendee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attended', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ptm_attendees',
            },
        ),
        migrations.CreateModel(
            name='PTMMeeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('parent_feedback', models.TextField(blank=True)),
                ('action_plan', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ptm_meetings',
            },
        ),
        migrations.CreateModel(
            name='PTM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptm_events', to='academics.class')),
            ],
            options={
                'db_table': 'ptm',
            },
        ),
    ]
