# Generated by Django 5.2.16 on 2026-07-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ptm', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptmattendee',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptm_attendances', to='users.parent'),
        ),
        migrations.AddField(
            model_name='ptmmeeting',
            name='ptm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='ptm.ptm'),
        ),
        migrations.AddField(
            model_name='ptmmeeting',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptm_meetings', to='users.student'),
        ),
        migrations.AddField(
            model_name='ptmmeeting',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptm_meetings', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='ptmattendee',
            name='ptm_meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='ptm.ptmmeeting'),
        ),
    ]
