# Generated by Django 5.2.16 on 2026-08-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptm', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ptmmeeting',
            unique_together={('teacher', 'meeting_date', 'start_time', 'end_time')},
        ),
    ]
