# Generated by Django 5.2.16 on 2026-08-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_classsubject_unique_together_and_more'),
        ('ptm', '0004_ptm_school_ptmattendee_school_ptmmeeting_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ptm',
            unique_together={('class_obj', 'name')},
        ),
    ]
